### PR TITLE
Track dependencies with dep

### PR DESCRIPTION
**Pull request by stevenroose**
Makes it easier for developers to get started, plus makes sure we're all working with the same version of every dependency.

Simply use `dep ensure` when you pull in a change of `Gopkg.lock`.

### CODE REVIEW

**Comment by genofire** [comment]
I am a not a contributor - atm. But like go development - i hate these tools.
Use [git submodule](https://git-scm.com/docs/git-submodule)s in [vendor folder](https://blog.gopheracademy.com/advent-2015/vendor-folder/).

I believe only a `go get github.com/ortuman/jackal` to build and install jackel is most beautiful.

**Comment by stevenroose** [comment]
I disagree with that. And I think the realm of vendoring tools in the Go ecosystem vouches for that.

In the future, vgo might make dependency vendoring obsolete, but for now I think this is the best way.

**Comment by ortuman** [comment]
Current PR breaks CI on OS X

https://travis-ci.org/ortuman/jackal/builds/369219983?utm_source=github_status&utm_medium=notification

Please, fix.

**Comment by stevenroose** [comment]
That should be fixed now, let's wait what Travis says :)

**Pull request merged**
