### PR TITLE
Run go mod tidy

### PR DESCRIPTION
**Pull request by SamWhited**
Deps have gotten out of sync; I fixed it by running `go mod tidy`.

### CODE REVIEW

**Comment by SamWhited** [comment]
Test failure appears to be unrelated; Launchpad uses Bazaar, not Git, and it's not installed on the OSX image.

**Comment by ortuman** [comment]
Oh! I see 😮 

I’ll chack it later! Thx 🙏🏻

**Comment by ortuman** [comment]
Weird. I just ran `go mod tidy` pushing on `master`and it all went well. 👍 

Closing this PR.

**Comment by SamWhited** [comment]
I had forgotten that a bug was fixed in the version of Go I'm using that may cause it to add a few indirect deps that would otherwise get left out. That's probably the difference we're seeing. It's not worth worrying about until Go 1.12 comes out with the fix (though if you wanted to make sure you're using the latest and greatest you could try with Go 1.12 beta 1).

**Pull request closed without merging**
