### PR TITLE
scripts: do not install utilities on users system

### PR DESCRIPTION
**Pull request by SamWhited**
Previously the genproto script would pollute the users $GOBIN with a
specific version of two tools for generating protobuf files, overwriting
the users existing versions if they already had these tools installed.
This patch depends on those tools in go.mod so that they can be built,
downloaded, and used with go run and don't need to be installed on the
users system. As a bonus, all versioning information is now in go.mod
instead of spread over go.mod and a script.

I can't really test this locally (as the script also appears to operate in GOPATH mode which hasn't been used for a while).

### CODE REVIEW

**Comment by ortuman** [comment]
Sweet @SamWhited! 👏 👏 👏 

> I can't really test this locally (as the script also appears to operate in GOPATH mode which hasn't been used for a while).

The script is intended to be run from the root folder via `make proto` command. I did it locally, and it worked great. Also, all proto files were updated with the new tool comment header. Have you tried this?

**Comment by SamWhited** [comment]
Right, that will complain about GOPATH not being found (because GOPATH mode is deprecated and I no longer have the environment variable set or any GOPATH with Go files in it for it to use).

**Comment by ortuman** [comment]
I see. I forgot I had `GOPATH` variable set (a legacy from the old days). 🤦‍♂️  

I wonder if we should follow a similar approach as the `go install` command.

Here's the official help reference: 

```
Executables are installed in the directory named by the GOBIN environment
variable, which defaults to $GOPATH/bin or $HOME/go/bin if the GOPATH
environment variable is not set. Executables in $GOROOT
are installed in $GOROOT/bin or $GOTOOLDIR instead of $GOBIN.
```

We could first check whether `GOPATH` variable is set, and if not, fallback to the `$HOME/go/bin` path. Sounds that ok? wdyt?

**Comment by SamWhited** [comment]
The GOPATH isn't being used to install the commands, it's being used to find protobuf files for stravaganza, I think? The problem is there is no central location where source files are stored now, and the only thing I can find online is that you're supposed to rely on a big heavy build system to do this for you. Since we don't have that, I think it's fine to leave GOPATH setup if you're still using it, it just won't be as portable for everyone. Or we can try to fix that in a later PR, it's not really related to not installing binaries. Whatever you want to do though, and of course if I'm misunderstanding anything, sorry about that! I normally avoid protobuf with a 10 foot pole and have largely forgotten how it works since I no longer use them for my job.

**Comment by SamWhited** [comment]
I had an idea and pushed another commit that fixes this to work in Go module mode. TL;DR we run `go mod vendor` to put all the dependencies in the local directory, then we rename the vendor dir (to avoid `go run` using it instead of the module cache), then we point `protoc` at the new vendored dependencies instead of `GOPATH`. At the end of the script we remove them to clean up. I can remove this commit if you don't like the solution, or split it out into another PR if you prefer.

**Comment by SamWhited** [comment]
I should also note that it's quite possible there is a better way to do this, but the workaround works on my machine. I do not know what the correct or idiomatic way to do this is.

**Pull request closed without merging**
